{
    'name': 'Lounge Management System (LMS)',
    'summary': 'Backend APIs and models for airport lounge access, built for Flutter frontend',
    'version': '18.0.1.0.0',
    'category': 'Operations/Lounge',
    'author': 'Idris Eslam Idris',
    'license': 'OEEL-1',
    'website': '',
    'depends': ['base', 'account', 'contacts', 'product', 'branch'],
    "data": [
        "data/sequence.xml",
        "reports/voucher.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/catalog/ffp_program.xml",
		"views/catalog/ffp_tier.xml",
        "views/catalog/lms_lounge_views.xml",
        "views/catalog/branch.xml",
        "views/catalog/capsule.xml",
        "views/catalog/capsule_unavailability.xml",
        "views/catalog/capsule_service.xml",
        "views/catalog/res_config.xml",
		"views/catalog/business_partner.xml",
		"views/catalog/acceptance_rules.xml",
		"views/catalog/facility.xml",
		"views/catalog/services.xml",
        "views/business/lms_override_views.xml",
        "views/business/lms_visit_views.xml",
        "views/business/voucher.xml",
        "views/business/reservation.xml",
        "views/menu.xml",
],
    'application': True,
    'installable': True,
}
